In [1]:
import numpy as np

In [3]:
a1=np.array([10,20,30])
a2=np.array([30,100,70])
print(a1)
print(a2)
print(a1+a2)

[10 20 30]
[ 30 100  70]
[ 40 120 100]


In [15]:
a=np.array([10,30,"20"])
print(a)
a3=np.array([10,30,20.0])
print(a3)

['10' '30' '20']
[10. 30. 20.]
