In [6]:
import numpy as np

In [8]:
a1=np.array([10,20,30])
a2=np.array([30,100,70])
print(a1)
print(a2)
print(a1+a2)

[10 20 30]
[ 30 100  70]
[ 40 120 100]


In [10]:
a=np.array([10,30,"20"])
print(a)
a3=np.array([10,30,20.0])
print(a3)

['10' '30' '20']
[10. 30. 20.]


In [12]:
arr=np.array([10,120,30,40,50])
a.shape

(3,)

In [14]:
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [16]:
np.arange(0,20,2).shape

(10,)

In [18]:
np.arange(0,20,2).reshape((2,5))

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18]])

In [20]:
np.random.randint(20,40,7)

array([36, 25, 31, 36, 32, 33, 34])

In [32]:
#create an array of 5X6 having values values from standard normal distribution
np.random.randn(5,6)

array([[ 0.83491575,  1.20098027,  0.16483591,  0.13208073,  0.91134395,
         0.1902496 ],
       [-0.03857284, -0.77470664, -0.2384823 ,  1.37949928,  0.79140878,
        -1.02431482],
       [ 0.86602609,  0.65788881, -1.2695906 , -0.20620193,  0.67420726,
         0.45798509],
       [ 0.09247028, -1.08569216, -1.3962601 ,  2.67958709, -1.02846434,
         1.51033352],
       [-1.22890741,  0.20839925, -1.01084518, -0.87038512, -0.47787319,
        -0.60922722]])

In [38]:
np.random.random_sample(2)

array([0.75361024, 0.44473303])